from src.config.config import (
    SELECTED_CLASSES, TASK_1, TASK_2, TASK_3, TASK_4,
    CLASSES_20, CLASSES_30, CLASSES_40, CLASSES_50,
    BATCH_SIZE, CLIP_LEN, CROP_SIZE, RESIZE_HEIGHT,
    FRAME_RATE, TRAIN_SPLIT, SEED, DROPOUT_P,
    DATASET_ROOT, OUTPUT_ROOT,
    BASE_ROOT, TASK1_ROOT, TASK2_ROOT, TASK3_ROOT, TASK4_ROOT,
    RESNET50_PATH, spatial_transform,
)
